name: Test

on:
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true
      - run: npm run build
      - run: npm test
